#ifndef D20_PARSING_EVENT
#define D20_PARSING_EVENT

typedef enum {
    PARSING_EVENT_VERSION,
    PARSING_EVENT_HELP,
    PARSING_EVENT_ERROR,
    PARSING_EVENT_SUCCESS
} PARSING_EVENT;

#endif  // D20_PARSING_EVENT